[package]
name = "c-guest-host"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { path = "../../../risc0/zkvm" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
anyhow = "1.0"
